# Generated by Django 4.2.4 on 2023-08-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage', models.CharField(max_length=10)),
                ('current', models.CharField(max_length=10)),
                ('power', models.CharField(max_length=10)),
                ('energy', models.CharField(max_length=10)),
            ],
        ),
    ]
